# Generated by Django 3.1.3 on 2020-12-04 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plagiarism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('c', 'C'), ('cc', 'C++'), ('java', 'JAVA'), ('ml', 'ML'), ('pascal', 'PASCAL'), ('ada', 'ADA'), ('lisp', 'LISP'), ('scheme', 'SCHEME'), ('haskell', 'HASKELL'), ('fortran', 'FORTRAN'), ('vhdl', 'VHDL'), ('verilog', 'VERILOG'), ('perl', 'PERL'), ('matlab', 'MATLAB'), ('python', 'PYTHON'), ('mips', 'MIPS'), ('prolog', 'PROLOG'), ('spice', 'SPICE'), ('vb', 'VISUAL BASIC'), ('csharp', 'C#'), ('modula2', 'MODULA2'), ('a8086', 'a8086'), ('javascript', 'JAVASCRIPT'), ('plsql', 'PLSQL')], default='python', max_length=100)),
                ('result', models.URLField(null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('base', models.BooleanField()),
                ('plagiarism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='plagiarism.plagiarism')),
            ],
        ),
    ]
