LANGUAGE_CHOICES = [        
    ('c','C'),
    ('cc','C++'),
    ('java','JAVA'),
    ('ml','ML'),
    ('pascal','PASCAL'),
    ('ada','ADA'),
    ('lisp','LISP'),
    ('scheme','SCHEME'),
    ('haskell','HASKELL'),
    ('fortran','FORTRAN'),
    ('vhdl','VHDL'),
    ('verilog','VERILOG'),
    ('perl','PERL'),
    ('matlab','MATLAB'),
    ('python','PYTHON'),
    ('mips','MIPS'),
    ('prolog','PROLOG'),
    ('spice','SPICE'),
    ('vb','VISUAL BASIC'),
    ('csharp','C#'),
    ('modula2','MODULA2'),
    ('a8086','a8086'),
    ('javascript','JAVASCRIPT'),
    ('plsql','PLSQL')
]

EXTENSION_OF = {      
    'c'          : ['c'],
    'cc'         : ['cpp'],
    'java'       : ['java'],
    'python'     : ['py'],
    'javascript' : ['js'],
    'csharp'     : ['cs'],
    'perl'       : ['pl','PL'],
    'pascal'     : ['pas'],
    'fortran'    : ['f90', 'for', 'f'],
    'matlab'     : ['m','M'],
    'ml'         : ['ml'],
    'ada'        : ['ada'],
    'lisp'       : ['lsp'],
    'scheme'     : ['scm','ss'],
    'haskell'    : ['hs'],
    'vhdl'       : ['vhd'],
    'verilog'    : ['v','vh'],
    'mips'       : ['s','asm'],
    'prolog'     : ['pl','pro'],
    'spice'      : ['cir','inp','txt'],
    'vb'         : ['vb'],
    'modula2'    : ['mod','m2','def','MOD','DEF','mi','md'],
    'a8086'      : ['asm'],
    'plsql'      : ['pks','pkb']
}